### ISSUE TITLE
Allow async=false via prop attributes

### ISSUE THREAD

**Issue by modestjoust** [blueberryapps/react-load-script#11]
Hey, it looks like async is set to true (1) in src/index:92 after custom attributes are set (src/index:88). Is it possible to be able to set async to false via custom attributes?

Thanks!

**Comment by modestjoust** [comment]
I can submit PR if you think this checks out?

**Comment by jakubkottnauer** [comment]
Hi @modestjoust, sure thing, PRs always welcome!

**Comment by modestjoust** [comment]
Thanks @jakubkottnauer, just submitted! Let me know if I can do anything else!

**Comment by jakubkottnauer** [comment]
Merged, thanks a lot 👍
