### ISSUE TITLE
[Feature Request]: Support for async and defer attributes

### ISSUE THREAD

**Issue by json2d** [blueberryapps/react-load-script#16]
Hi, I would like to see support for the `async` and `defer` attributes. Seems like it would be pretty straightforward to implement. Any objections?

**Comment by patrick-mcdougle** [comment]
All scripts added this way are async by default. You can't really defer a dynamically injected script.

**Comment by mationai** [comment]
Please add noModule attributes or ="true" as in https://github.com/facebook/react/pull/11900
