### ISSUE TITLE
About prop-types

### ISSUE THREAD

**Issue by chimilord** [blueberryapps/react-load-script#4]
Hellos guys, 

More than an issue, is a question, when I added the component I got this warning:

`Warning: Failed propType: Calling PropTypes validators directly is not supported by the `prop-types` package`

I read about this but I can't fix it.

Thanks!

**Comment by jakubkottnauer** [comment]
Hi @chimilord, this is due to version inconsistencies, similar to here https://github.com/reactjs/react-redux/issues/669

What version of react are you using?

**Comment by chimilord** [comment]
Hi @jakubkottnauer 

Oh I see, I'm using `react 15.1.0`.

Thanks!
